name: 'Slack Notify'
description: 'This action sending Slack notifications'

inputs:
  channel:
    description: "Target slack channel"
    required: true
  username:
    description: "Sender"
    required: true
  icon:
    description: "Message icon"
    required: true
  message:
    description: "Message text"
    required: true
  slack_webhook:
    description: "Slack webhook (use secret)"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
